# Generated by Django 4.0.4 on 2022-06-12 20:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название слайда')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок слайда')),
                ('text', models.TextField(verbose_name='Текст слайда')),
                ('button_text', models.CharField(max_length=20, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, max_length=250, verbose_name='Ссылка по кнопке')),
                ('image', models.ImageField(help_text='Изображения только в формате jpg', upload_to='images/main_page', verbose_name='Картинка слайда')),
            ],
            options={
                'verbose_name': 'Слайд на главной странице',
                'verbose_name_plural': 'Слайды на главной странице',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название партнёра')),
                ('short_description', models.CharField(blank=True, max_length=250, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='images/partners', verbose_name='Логотип партнёра')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Подробное описание')),
                ('url', models.URLField(blank=True, help_text='Если оставить пустым, нельзя будет указать ссылку на страницу с оборудованием', verbose_name='Ссылка на страницу с оборудованием')),
                ('slug', models.SlugField(help_text='Если оставить пустым, заполнится транслитом название партнёра', null=True, unique=True, verbose_name='Url партнёра на сайте')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
