# Generated by Django 4.0.4 on 2022-05-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название слайда')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок слайда')),
                ('text', models.TextField(verbose_name='Текст слайда')),
                ('button_text', models.CharField(max_length=20, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, max_length=250, verbose_name='Ссылка по кнопке')),
                ('image', models.ImageField(help_text='Изображения только в формате jpg', upload_to='images/main_page', verbose_name='Картинка слайда')),
            ],
            options={
                'verbose_name': 'Слайд на главной странице',
                'verbose_name_plural': 'Слайды на главной странице',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название партнёра')),
                ('image', models.ImageField(upload_to='images/partners', verbose_name='Логотип партнёра')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Партнёр внизу страницы',
                'verbose_name_plural': 'Партнёры внизу страницы',
            },
        ),
    ]
