# Generated by Django 4.0.4 on 2022-06-09 21:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(help_text='Если оставить пустым, заполнится транслитом название партнёра', null=True, unique=True, verbose_name='Url партнёра на сайте'),
        ),
        migrations.AddField(
            model_name='partner',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка на страницу с оборудованием'),
        ),
    ]
