# Generated by Django 4.0.4 on 2022-05-08 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название партнёра')),
                ('logo', models.ImageField(upload_to='images/patners', verbose_name='Логотип партнёра')),
            ],
            options={
                'verbose_name': 'Партнёр внизу страницы',
                'verbose_name_plural': 'Партнёры внизу страницы',
            },
        ),
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'verbose_name': 'Слайд на главной странице', 'verbose_name_plural': 'Слайды на главной странице'},
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(help_text='Изображения только в формате jpg', upload_to='images/main_page', verbose_name='Картинка слайда'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='order_id',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Порядковый номер слайда'),
        ),
    ]
