# Generated by Django 4.0.4 on 2022-08-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_partner_options_partner_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'ordering': ['my_order'], 'verbose_name': 'Слайд на главной странице', 'verbose_name_plural': 'Слайды на главной странице'},
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
