# Generated by Django 4.0.4 on 2022-05-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_rename_logo_partner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitem',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='images/partners', verbose_name='Логотип партнёра'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название партнёра'),
        ),
    ]
