# Generated by Django 4.0.4 on 2022-05-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_remove_carouselitem_order_id_alter_partner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='button_url',
            field=models.URLField(blank=True, max_length=250, verbose_name='Ссылка по кнопке'),
        ),
    ]
