# Generated by Django 4.0.4 on 2022-05-24 20:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, help_text='Если оставить пустым, заполнится транслитом название категории', max_length=70, verbose_name='URL категории')),
            ],
            options={
                'verbose_name': 'Категория проектов',
                'verbose_name_plural': 'Категории проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/projects/detail/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проекта',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('title', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Основной текст')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectcategory', verbose_name='Категории')),
                ('images', models.ManyToManyField(related_name='project_images', to='projects.projectimage', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'title'), name='unique_name_for_title'),
        ),
    ]
