# Generated by Django 4.0.4 on 2022-06-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='event_bool',
            field=models.BooleanField(default=False, help_text='Отметить если необходимо указать дату проведения и место', verbose_name='Мероприятие'),
        ),
    ]
