# Generated by Django 4.0.4 on 2022-05-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_name_alter_news_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
