# Generated by Django 4.0.4 on 2022-06-12 20:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('short_description', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('image', models.ImageField(help_text='Изображения только в формате png 120*120', upload_to='images/services/', verbose_name='Значок на главной странице')),
                ('slug', models.SlugField(help_text='Если оставить пустым, заполнится транслитом название услуги', null=True, unique=True, verbose_name='Url услуги на сайте')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Подробное описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/services/detail/', verbose_name='Изображения в карусели услуги')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceitem', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Изображение услуги',
                'verbose_name_plural': 'Изображения услуги',
            },
        ),
    ]
