# Generated by Django 4.0.4 on 2022-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('short_description', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('image', models.ImageField(help_text='Изображения только в формате png 120*120', upload_to='images/services/', verbose_name='Значок на главной странице')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
