# Generated by Django 4.0.4 on 2022-06-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='slug',
            field=models.SlugField(help_text='Если оставить пустым, заполнится транслитом название услуги', null=True, unique=True, verbose_name='Url услуги на сайте'),
        ),
    ]
