# Generated by Django 4.0.4 on 2022-05-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItemDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/services/detail/', verbose_name='Изображения в карусели услуги')),
            ],
            options={
                'verbose_name': 'Изображение услуги',
                'verbose_name_plural': 'Изображения услуги',
            },
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceItem',
        ),
        migrations.CreateModel(
            name='ServiceItemDetail',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.serviceitem', verbose_name='Детальное описание')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceitemdetailimage', verbose_name='Изображения в карусели')),
            ],
            options={
                'verbose_name': 'Услуга детальное описание',
                'verbose_name_plural': 'Услуги детальное описание',
            },
        ),
    ]
