# Generated by Django 4.0.4 on 2022-05-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceitemdetailimage_rename_service_serviceitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceItemDetailImage',
            new_name='ServiceCarouselImage',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='carousel_images',
            field=models.ManyToManyField(to='services.servicecarouselimage', verbose_name='Изображения в карусели'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Адрес услуги в url сайта'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='text',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.DeleteModel(
            name='ServiceItemDetail',
        ),
    ]
