# Generated by Django 4.0.4 on 2022-08-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceitem_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecarouselimage',
            options={'ordering': ['my_order'], 'verbose_name': 'Изображение услуги', 'verbose_name_plural': 'Изображения услуги'},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ['my_order'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='servicecarouselimage',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
