# Generated by Django 4.0.4 on 2022-05-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_serviceitemdetailimage_servicecarouselimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='slug',
            field=models.SlugField(help_text='Если оставить пустым, заполнится транслитом название услуги', null=True, unique=True, verbose_name='Адрес услуги в url сайта'),
        ),
    ]
