# Generated by Django 4.0.4 on 2022-06-12 22:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название бренда')),
                ('slug', models.SlugField(blank=True, help_text='Если оставить пустым, заполнится транслитом название категории', max_length=70, verbose_name='URL бренда')),
                ('image', models.ImageField(upload_to='images/equipment-category/brend', verbose_name='Изображение бренда')),
            ],
            options={
                'verbose_name': 'Бренд оборудования',
                'verbose_name_plural': 'Бренды оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, help_text='Если оставить пустым, заполнится транслитом название категории', max_length=70, verbose_name='URL категории')),
                ('image', models.ImageField(upload_to='images/equipment-category', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название оборудования')),
                ('title', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('tech_data', ckeditor.fields.RichTextField(verbose_name='Технические характеристики')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, help_text='Если оставить пустым, заполнится транслитом название категории', max_length=70, verbose_name='URL категории')),
                ('image', models.ImageField(upload_to='images/equipment-category/subcategory', verbose_name='Изображение подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='equipment.equipmentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория оборудования',
                'verbose_name_plural': 'Подкатегории оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentItemYoutubeVideoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=150, verbose_name='Ссылка на видео YouTube')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentitem', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Ссылка на видео YouTube',
                'verbose_name_plural': 'Ссылки на видео YouTube',
            },
        ),
        migrations.CreateModel(
            name='EquipmentItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/equipment-category/items/images', verbose_name='Изображения в карусели еденицы оборудования')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentitem', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Изображение единицы оборудования',
                'verbose_name_plural': 'Изображения единицы оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentItemDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='images/equipment-category/items/documents', verbose_name='Изображения в карусели еденицы оборудования')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentitem', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Документ единицы оборудования',
                'verbose_name_plural': 'Документы единицы оборудования',
            },
        ),
        migrations.AddConstraint(
            model_name='equipmentitem',
            constraint=models.UniqueConstraint(fields=('name', 'title'), name='unique_name_for_title_equipment'),
        ),
        migrations.AddField(
            model_name='equipmentbrend',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='equipment.equipmentsubcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddConstraint(
            model_name='equipmentsubcategory',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_subcategory_for_category'),
        ),
    ]
