# Generated by Django 4.0.4 on 2022-06-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='subcategory',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentsubcategory', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentitemdocument',
            name='document',
            field=models.FileField(upload_to='images/equipment-category/items/documents', verbose_name='Документ во вложении'),
        ),
        migrations.AlterField(
            model_name='equipmentitemimage',
            name='image',
            field=models.ImageField(upload_to='images/equipment-category/items/images', verbose_name='Изображения в карусели единицы оборудования'),
        ),
    ]
