# Generated by Django 4.0.4 on 2022-06-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipmentitem_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='brend',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentbrend', verbose_name='Бренд'),
            preserve_default=False,
        ),
    ]
