# Generated by Django 4.0.4 on 2022-06-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentitem_brend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentbrend',
            old_name='slug',
            new_name='brend_slug',
        ),
    ]
