# Generated by Django 4.0.4 on 2022-06-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_rename_slug_equipmentbrend_brend_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentsubcategory',
            old_name='slug',
            new_name='sub_slug',
        ),
    ]
