# Generated by Django 4.0.4 on 2022-06-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_rename_slug_equipmentsubcategory_sub_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentcategory',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='equipmentsubcategory',
            old_name='sub_slug',
            new_name='subcategory_slug',
        ),
    ]
