# Generated by Django 4.0.4 on 2022-06-30 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_rename_slug_equipmentcategory_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastViewedEquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200, verbose_name='Ключ сессии')),
                ('equipment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentitem', verbose_name='Оборудование')),
            ],
        ),
    ]
