# Generated by Django 4.0.4 on 2022-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_lastviewedequipmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbrend',
            name='image',
            field=models.ImageField(help_text='Для лучшего отображения должно быть равное соотношение сторон', upload_to='images/equipment-category/brend', verbose_name='Изображение бренда'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='image',
            field=models.ImageField(help_text='Для лучшего отображения должно быть равное соотношение сторон', upload_to='images/equipment-category', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='equipmentitemimage',
            name='image',
            field=models.ImageField(help_text='Для лучшего отображения должно быть равное соотношение сторон', upload_to='images/equipment-category/items/images', verbose_name='Изображения в карусели единицы оборудования'),
        ),
        migrations.AlterField(
            model_name='equipmentsubcategory',
            name='image',
            field=models.ImageField(help_text='Для лучшего отображения должно быть равное соотношение сторон', upload_to='images/equipment-category/subcategory', verbose_name='Изображение подкатегории'),
        ),
    ]
