# Generated by Django 4.0.4 on 2022-08-17 16:26

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipmentbrend_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Пожалуйста, представьтесь', max_length=100, verbose_name='Ваше имя')),
                ('email', models.EmailField(help_text='Укажите, чтобы связаться с Вами', max_length=150, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Необязательно', max_length=128, region=None, verbose_name='Телефон')),
                ('text', models.TextField(help_text='Укажите количество, так же можно указать необходимую периферию и комплектующие', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Ваш запрос')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы оборудования',
            },
        ),
    ]
