# Generated by Django 4.0.4 on 2022-09-18 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_alter_equipmentitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentrequest',
            options={'verbose_name': 'Запрос оборудования', 'verbose_name_plural': 'Запросы оборудования'},
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Ваш запрос'),
        ),
    ]
