# Generated by Django 4.0.4 on 2022-09-27 18:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_alter_equipmentrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitem',
            name='tech_data',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Технические характеристики'),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
    ]
