# Generated by Django 4.0.4 on 2022-08-17 15:33

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default="111", max_length=128, region=None),
            preserve_default=False,
        ),
    ]
