# Generated by Django 4.0.4 on 2022-08-17 15:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Общий вопрос', 'verbose_name_plural': 'Общие вопросы'},
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(help_text='Укажите, чтобы связаться с Вами', max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(help_text='Пожалуйста, представьтесь', max_length=100, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='question',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Необязательно', max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Ваш вопрос'),
        ),
    ]
