# Generated by Django 4.0.4 on 2022-08-17 15:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_options_alter_question_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Необязательно', max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
