# Generated by Django 4.0.4 on 2022-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('vocation', models.CharField(max_length=50, verbose_name='Должность')),
                ('image', models.ImageField(help_text='Изображения только в формате jpg', upload_to='images/club/members/', verbose_name='Фотография')),
                ('email', models.EmailField(blank=True, help_text='Необязательно', max_length=150, unique=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Член клуба',
                'verbose_name_plural': 'Члены клуба',
            },
        ),
    ]
