# Generated by Django 4.0.4 on 2022-05-25 22:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('vocation', models.CharField(max_length=50, verbose_name='Должность')),
                ('image', models.ImageField(help_text='Изображения только в формате jpg', upload_to='images/club/members/', verbose_name='Фотография')),
                ('email', models.EmailField(blank=True, help_text='Необязательно', max_length=150, unique=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Член клуба',
                'verbose_name_plural': 'Члены клуба',
            },
        ),
        migrations.CreateModel(
            name='HalfStaticPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/club/staticpages/', verbose_name='Изображения в карусели услуги')),
            ],
            options={
                'verbose_name': 'Изображение статических страниц',
                'verbose_name_plural': 'Изображения статических страниц',
            },
        ),
        migrations.CreateModel(
            name='HalfStaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL страницы')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('images', models.ManyToManyField(to='club.halfstaticpageimage', verbose_name='Изображения на статических страницах')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
    ]
