# Generated by Django 4.0.4 on 2022-05-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='email',
            field=models.EmailField(help_text='Необязательно', max_length=150, unique=True, verbose_name='Электронная почта'),
        ),
    ]
