# Generated by Django 4.0.4 on 2022-05-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='telegram_contact',
            field=models.URLField(blank=True, help_text='Необязательно', max_length=100, verbose_name='Ссылка на профиль телеграм'),
        ),
    ]
