# Generated by Django 4.0.4 on 2022-05-25 20:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_clubmember_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalfStaticPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/club/staticpages/', verbose_name='Изображения в карусели услуги')),
            ],
            options={
                'verbose_name': 'Изображение статических страниц',
                'verbose_name_plural': 'Изображения статических страниц',
            },
        ),
        migrations.CreateModel(
            name='HalfStaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL страницы')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('images', models.ManyToManyField(to='club.halfstaticpageimage', verbose_name='Изображения на статических страницах')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
    ]
