# Generated by Django 4.0.4 on 2022-06-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_clubmember_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmember',
            name='email',
        ),
        migrations.AddField(
            model_name='clubmember',
            name='achievements',
            field=models.TextField(default=1, verbose_name='Достижения'),
            preserve_default=False,
        ),
    ]
