# Generated by Django 4.0.4 on 2022-06-27 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_change_static_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halfstaticpageimage',
            options={'verbose_name': 'Изображение карусели статических страниц', 'verbose_name_plural': 'Изображения карусели статических страниц'},
        ),
        migrations.AlterField(
            model_name='halfstaticpageimage',
            name='image',
            field=models.ImageField(upload_to='images/club/staticpages/', verbose_name='Изображения для вставки в карусель'),
        ),
        migrations.CreateModel(
            name='HalfStaticPageYoutubeVideoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=150, verbose_name='Ссылка на видео YouTube')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.halfstaticpage', verbose_name='Статическая страница')),
            ],
            options={
                'verbose_name': 'Ссылка на видео YouTube',
                'verbose_name_plural': 'Ссылки на видео YouTube',
            },
        ),
    ]
