# Generated by Django 4.0.4 on 2022-08-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_halfstaticpageimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmember',
            options={'ordering': ['my_order'], 'verbose_name': 'Член клуба', 'verbose_name_plural': 'Члены клуба'},
        ),
        migrations.AlterModelOptions(
            name='halfstaticpageimage',
            options={'ordering': ['my_order'], 'verbose_name': 'Изображение карусели статических страниц', 'verbose_name_plural': 'Изображения карусели статических страниц'},
        ),
        migrations.AddField(
            model_name='clubmember',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='halfstaticpageimage',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
