# Generated by Django 4.0.1 on 2022-01-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Название изображения")),
                ("image", models.ImageField(upload_to="images/main_page", verbose_name="Фотография")),
            ],
            options={
                "verbose_name": "Изображение на странице заставки",
                "verbose_name_plural": "Изображения на странице заставки",
            },
        ),
    ]
