# Generated by Django 4.0.1 on 2022-01-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainimage',
            name='index',
            field=models.SmallIntegerField(default=1, max_length=10, verbose_name='Порядок отображения на странице'),
            preserve_default=False,
        ),
    ]
