# Generated by Django 4.0.1 on 2022-01-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_page', '0002_mainimage_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='index',
            field=models.SmallIntegerField(verbose_name='Порядок отображения на странице'),
        ),
    ]
