# Generated by Django 4.0.1 on 2022-01-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_page', '0002_add_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'FaceBook'), ('vk', 'VKontakte')], max_length=9, verbose_name='Тип социальной сети')),
                ('url', models.URLField(verbose_name='Ссылка на социальную сеть')),
                ('is_visible', models.BooleanField(default=False, help_text='Показывать это соц. сеть на главной?', verbose_name='Отображение на главной странице')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ('type',),
            },
        ),
    ]
